### ISSUE TITLE
Error on demo (after installation)

### ISSUE THREAD

**Issue by fundup** [Victoire/demo#8]
request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Warning: array_search() expects parameter 2 to be array, boolean given at /var/www/victoireCMS/eloVicBlog/vendor/victoire/victoire/Bundle/CoreBundle/EventSubscriber/EntityProxySubscriber.php line 61) {"exception":"[object](Symfony\Component\Debug\Exception\ContextErrorException%28code: 0%29: Warning: array_search%28%29 expects parameter 2 to be array, boolean given at /var/www/victoireCMS/eloVicBlog/vendor/victoire/victoire/Bundle/CoreBundle/EventSubscriber/EntityProxySubscriber.php:61)"} []

**Comment by paulandrieux** [comment]
Hi, do you have this issue after a "php bin/console cache:warmup" ?

**Comment by fundup** [comment]
I don't and running php bin/console cache:warmup seems to solved this issue. Thanks
